// <auto-generated />
using Demo.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.WebApi.Migrations
{
    [DbContext(typeof(DemoContext))]
    [Migration("20250926102633_seeding")]
    partial class seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("tblCities", "City");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CountryId = 1,
                            Name = "Antwerpen",
                            Population = 10000000L
                        },
                        new
                        {
                            Id = -2,
                            CountryId = 1,
                            Name = "Brussel",
                            Population = 20000000L
                        },
                        new
                        {
                            Id = -3,
                            CountryId = 1,
                            Name = "Gent",
                            Population = 5000000L
                        },
                        new
                        {
                            Id = -4,
                            CountryId = 1,
                            Name = "Brugge",
                            Population = 2000000L
                        });
                });

            modelBuilder.Entity("Demo.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("tblCountries", "Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "België"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nederland"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Frankrijk"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Duitsland"
                        });
                });

            modelBuilder.Entity("Demo.Domain.City", b =>
                {
                    b.HasOne("Demo.Domain.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Demo.Domain.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
